# Generated by Django 5.0.2 on 2024-03-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyze_file', '0002_delete_userprofilemedia'),
        ('file_upload_router', '0005_remove_userprofilemedia_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload_router.project')),
            ],
        ),
    ]
