# Generated by Django 5.0.2 on 2024-03-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_router', '0005_remove_userprofilemedia_profile_and_more'),
        ('summary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprompts',
            name='file',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='file_upload_router.userprofilemedia'),
            preserve_default=False,
        ),
    ]
