# Generated by Django 5.0.2 on 2024-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=10)),
                ('file_url', models.URLField(max_length=1024)),
            ],
        ),
    ]
