# Generated by Django 5.0.2 on 2024-03-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_router', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileRecord',
        ),
    ]
