# Generated by Django 5.0.2 on 2024-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_router', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemedia',
            name='project_name',
            field=models.CharField(default='myproject', max_length=255),
            preserve_default=False,
        ),
    ]
