# Generated by Django 5.0.2 on 2024-03-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('file_upload_router', '0004_userprofilemedia_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemedia',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofilemedia',
            name='project_name',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='auth_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofilemedia',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='file_upload_router.project'),
            preserve_default=False,
        ),
    ]
